#!/usr/bin/env bash
# making a script that makes me happier
# checking the updates if found
sudo apt-get update

#checking for the packege to be found
sudo apt-get install -y nginx

# making the parent directory
sudo mkdir -p /var/www/html

#making the file
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

printf %s "server {
   listen 80;
   listen [::]:80 default_server;
   root /etc/nginx/html;
   index index.html index.htm;
}" > /etc/nginx/sites-available/default

# restarting the server
service nginx restart
