#!/usr/bin/env bash
# making a script that makes me happier
sudo su

# checking the updates if found
apt-get update

#checking for the packege to be found
apt-get install -y nginx

# making the parent directory
mkdir -p /etc/nginx/html

#making the file
touch /etc/nginx/html/index.html
echo "Hello World!" > etc/nginx/html/index.html

printf %s "server {
   listen 80;
   listen [::]:80 default_server;
   root /etc/nginx/html;
   index index.html index.htm;
}" > /etc/nginx/sites-available/default

# restarting the server
service nginx restart
