#!/usr/bin/env bash
# this script is dump

echo $$ > /var/run/myscript.pid

handleINT(){
	echo "Y U no love me?!"
}

handleTERM(){
	echo "I hate the kill command"
	cleanup
}

cleanup(){
	rm -f /var/run/myscript.pid
	exit
}

trap handleINT 2
trap handleTERM 15
trap cleanup 3

while true;do
	echo "To infinity and beyond"
	sleep 2
done
