#!/usr/bin/env bash
# this bash print best school in 10 lines except for the line 9 it prints Hi

i=1
while [ "$i" -le 10 ]
do
	if [ "$i" -eq 10 ]
	then
		echo "Hi"
	fi	
	echo "Best School"
	i=$((i + 1))
done;
