#!/usr/bin/env bash
# This Bash files changes the IP addresses of the localhost and the facbook
cp /etc/hosts ~/hosts.new
sed -i /localhost$/d ~/hosts.new
echo -e "127.0.0.2\tlocalhost" >> ~/hosts.new
sed -i /facebook.com$/d ~/hosts.new
echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
